name: AlgoPublic build
run-name: AlgoPublic build ${{ inputs.releaseVersion }}
on:
  push:
    branches: [master, develop]
env:
  ARTIFACT_NAME: 'Algo PublicBots'
  BUILD_OUTPUT_FOLDER: .build/build.output

jobs:
  build:
    runs-on: windows-latest
    env:
      BuildScriptPath: .github/build/build.ps1
    strategy:
      matrix:
          node-version: [8.x, 10.x, 12.x, 13.x]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Run PowerShell script
      run: ${{env.BuildScriptPath}}

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: ${{ env.ARTIFACT_NAME }}
    #     path: ${{ env.BUILD_OUTPUT_FOLDER }}
    - name: Create a file
      run: echo ${{ matrix.node-version }} > my_file.txt
    - name: Accidentally upload to the same artifact via multiple jobs
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact ${{ matrix.node-version }}
        path: ${{ github.workspace }}